# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
  

   config.vm.define "rtr1" do |rtr1|
      rtr1.vm.box =  "IOS-XRv"

      rtr1.vm.network "forwarded_port", guest: 57777, host: 57777, auto_correct: true 

      # gig0/0/0/0 connected to "link1", gig0/0/0/1 connected to "link2"
      # auto_config is not supported for XR, set to false

      rtr1.vm.network :private_network, virtualbox__intnet: "link1", auto_config: false
      rtr1.vm.network :private_network, virtualbox__intnet: "link2", auto_config: false
      rtr1.vm.network :private_network, virtualbox__intnet: "link3", auto_config: false

      #Source a config file and apply it to XR
      rtr1.vm.provision "transfer_config", type: "file", source: "configs/rtr1_config", destination: "/home/vagrant/rtr_config"
      

      rtr1.vm.provision "apply_config", type: "shell" do |s|
          s.path =  "scripts/apply_config.sh"
          s.args = ["/home/vagrant/rtr_config"]
      end

      rtr1.vm.provider "virtualbox" do |v|
         v.memory = 4096
      end
    end


   config.vm.define "rtr2" do |rtr2|
      rtr2.vm.box =  "IOS-XRv"

      rtr2.vm.network "forwarded_port", guest: 57778, host: 57777, auto_correct: true
      # gig0/0/0/0 connected to "link1"  and  gig0/0/0/1 connected to "link2"
      # auto_config is not supported for XR, set to false

      rtr2.vm.network :private_network, virtualbox__intnet: "link1", auto_config: false
      rtr2.vm.network :private_network, virtualbox__intnet: "link4", auto_config: false

      #Source a config file and apply it to XR

      rtr2.vm.provision "transfer_config", type: "file", source: "configs/rtr2_config", destination: "/home/vagrant/rtr_config"

      rtr2.vm.provision "apply_config", type: "shell" do |s|
          s.path =  "scripts/apply_config.sh"
          s.args = ["/home/vagrant/rtr_config"]
      end

      rtr2.vm.provider "virtualbox" do |v|
         v.memory = 4096
     end
    end


   config.vm.define "rtr3" do |rtr3|
      rtr3.vm.box =  "bento/ubuntu-16.04"
      rtr3.vm.box_check_update = false
      rtr3.vm.network :private_network, virtualbox__intnet: "link2", ip: "11.1.1.20"

      rtr3.vm.provision "shell" do |s|
          s.path =  "scripts/install_quagga.sh"
          s.args = "rtr3"
      end
    end


   config.vm.define "devbox" do |devbox|
      devbox.vm.box =  "bento/ubuntu-16.04"
      devbox.vm.box_check_update = false
      devbox.vm.network "forwarded_port", guest: 2181, host: 2181, auto_correct: true
      devbox.vm.network "forwarded_port", guest: 3306, host: 3306, auto_correct: true
      devbox.vm.network "forwarded_port", guest: 9902, host: 9902, auto_correct: true
      devbox.vm.network "forwarded_port", guest: 8001, host: 8001, auto_correct: true
      devbox.vm.network "forwarded_port", guest: 5000, host: 5001, auto_correct: true
      devbox.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true

      # gig0/0/0/0 connected to "link1"  and  gig0/0/0/1 connected to "link2"
      # auto_config is not supported for XR, set to false

      devbox.vm.network :private_network, virtualbox__intnet: "link3", ip: "12.1.1.20"
      devbox.vm.network :private_network, virtualbox__intnet: "link4", ip: "13.1.1.20"

      #Source a config file and apply it to XR

      devbox.vm.provision "setup_openbmp", type: "shell" do |s|
          s.path =  "scripts/setup_openbmp.sh"
          s.env = {"http_proxy" => "#{ENV['http_proxy']}", "https_proxy" => "#{ENV['https_proxy']}", "insecure_registry" => "#{ENV['insecure_registry']}"}
      end

      devbox.vm.provider "virtualbox" do |v|
         v.memory = 6184
         v.cpus = 3
     end
    end

end
